config/routes.rb
Rails.application.routes.draw do
	# root 'pups#index'
	root "facts#index"
	resources :facts, only: [:new, :create, :show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/fact.rb
class Fact < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/facts_controller.rb
class FactsController < ApplicationController
	def index
		@fact = Fact.order("RANDOM()").first
	end

	def new
		@fact = Fact.new
	end

	def show
		@fact = Fact.find(params[:id])
	end

	def create
		@fact = Fact.create(fact_params)
		redirect_to @fact
	end

	private

	def fact_params
		params.require(:fact).permit(:content)
	end
end

app/controllers/pups_controller.rb
class PupsController < ApplicationController
	def index
		
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/facts_helper.rb
module FactsHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/puppy_helper.rb
module PuppyHelper
end

app/helpers/pups_helper.rb
module PupsHelper
end

app/views/facts/index.html.erb
<div class="dog container">
	<h1>Funny Dog Meme</h1>
	<%= image_tag 'dog_pic.png', class: 'img-fluid' %>
	
	<% if @fact %>
		<h1><%= @fact.content %></h1>
	<% end %>

	<div class="col-12 links">
    <%= link_to 'Contribute', new_fact_path, class: 'btn btn-danger' %>
    
  </div>
</div>

app/views/facts/new.html.erb
<h1>Enter Your Fact Details</h1>
<%= simple_form_for @fact do |f| %>
  <%= f.input :content %>
  <br />
  <%= f.submit 'Create', class: 'btn btn-danger' %>
<% end %>

app/views/facts/show.html.erb
<div class="dog container">
	<h1>Funny Dog Meme</h1>
	<%= image_tag 'dog_pic.png', class: 'img-fluid' %>
	<h1><%= @fact.content %></h1>

	<div class="col-12 links">
    <%= link_to 'Contribute', new_fact_path, class: 'btn btn-danger' %>
    
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <header>
    <title>Mjapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </header>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pups/index.html.erb
<div class="dog container">
	<h1>Funny Dog Meme</h1>
	<%= image_tag 'dog_pic.png', class: 'img-fluid' %>
	<h1><%= @fact.inspect %></h1>
</div>